[agent]
  interval = "30s"
  round_interval = true
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = "1ms"
  omit_hostname = true

#[[outputs.influxdb_v2]]
#  urls = ["http://<INFLUXDB_HOST>:8086"]
#  token = "$INFLUX_TOKEN"
#  organization = "raspberry"
#  bucket = "pytes"

[[outputs.file]]
  files = ["stdout"]
  data_format = "json"

[[inputs.http]]
  urls = ["http://<PYTES_PROXY_HOST>:8080/metrics"]
  method = "GET"
  interval = "5s"
  timeout = "10s"
  data_format = "json_v2"
  name_override = "summary"
  tagexclude = ["url"]

  [[inputs.http.json_v2]]
    timestamp_path = "host_ts_unix_ms"
    timestamp_format = "unix_ms"

    [[inputs.http.json_v2.object]]
      path = "summary"
      disable_prepend_keys = true
      included_keys = [
        "total_current_a",
        "total_power_w",
        "avg_soc_percent",
        "min_soc_percent",
        "max_soc_percent",
        "avg_module_voltage_v",
        "min_module_voltage_v",
        "max_module_voltage_v",
        "avg_module_temperature_c",
        "min_cell_voltage_v",
        "min_cell_voltage_module_id",
        "min_cell_voltage_cell",
        "max_cell_voltage_v",
        "max_cell_voltage_module_id",
        "max_cell_voltage_cell",
        "cell_delta_v",
        "avg_cell_voltage_v",
        "min_cell_temperature_c",
        "max_cell_temperature_c",
        "avg_cell_temperature_c",
      ]
  [inputs.http.tags]
    host = "pytes-proxy"      

[[inputs.http]]
  urls = ["http://<PYTES_PROXY_HOST>:8080/metrics"]
  method = "GET"
  interval = "5s"
  timeout = "10s"
  data_format = "json_v2"
  name_override = "batteries"
  tagexclude = ["url"]

  [[inputs.http.json_v2]]
    timestamp_path = "host_ts_unix_ms"
    timestamp_format = "unix_ms"

    [[inputs.http.json_v2.object]]
      path = "batteries"
      disable_prepend_keys = true
      tags = ["module_id"]
      included_keys = [
        "module_id",
        "voltage_v",
        "current_a",
        "power_w",
        "temperature_c",
        "soc_percent",
#        "capacity_mah",
        "cell0_v",
        "cell1_v",
        "cell2_v",
        "cell3_v",
        "cell4_v",
        "cell5_v",
        "cell6_v",
        "cell7_v",
        "cell8_v",
        "cell9_v",
        "cell10_v",
        "cell11_v",
        "cell12_v",
        "cell13_v",
        "cell14_v",
        "cell15_v",
      ]

  [inputs.http.tags]
    host = "pytes-proxy"
